// Shared rendering helpers for leagues.html and team.html.
// Each league has its own leagues/<slug>.json (listed in leagues/index.json),
// generated by scripts/export_league_data.py and rendered client-side.

const DEFAULT_LEAGUE = 'mens-northwest';

function escapeHtml(str) {
  return String(str ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

function pointsBadge(pts) {
  const p = parseFloat(pts);
  if (Number.isNaN(p)) return escapeHtml(pts);
  const cls = p >= 3 ? 'badge-green' : (p >= 2 ? 'badge-gold' : 'badge-red');
  return `<span class="badge ${cls}">${p} pts</span>`;
}

// 59.5 -> "59½"
function formatPoints(p) {
  if (p === null || p === undefined || p === '') return '';
  const n = Number(p);
  return Number.isInteger(n) ? String(n) : `${Math.floor(n)}½`;
}

function teamSeriesTotal(week) {
  return week.bowlers.reduce((sum, b) => sum + (parseInt(b.total, 10) || 0), 0);
}

function currentLeagueSlug() {
  const slug = new URLSearchParams(window.location.search).get('league');
  return slug && /^[a-z0-9-]+$/.test(slug) ? slug : DEFAULT_LEAGUE;
}

async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error('Could not load league data (' + res.status + ')');
  return res.json();
}

function loadLeagueIndex() {
  return fetchJson('leagues/index.json');
}

function loadLeagueData(slug = currentLeagueSlug()) {
  return fetchJson(`leagues/${slug}.json`);
}

function teamUrl(slug, teamId) {
  return `team.html?league=${encodeURIComponent(slug)}&id=${encodeURIComponent(teamId)}`;
}

function latestWeekNum(team) {
  return Math.max(...Object.keys(team.weeks).map(Number));
}
