// Shared rendering helpers for leagues.html and team.html.
// Both pages fetch leagues-data.json (generated by scripts/export_league_data.py
// from the bracket-system database) and render it client-side.

function escapeHtml(str) {
  return String(str ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

function pointsBadge(pts) {
  const p = parseFloat(pts);
  if (Number.isNaN(p)) return escapeHtml(pts);
  const cls = p >= 3 ? 'badge-green' : (p >= 2 ? 'badge-gold' : 'badge-red');
  return `<span class="badge ${cls}">${p} pts</span>`;
}

function teamSeriesTotal(week) {
  return week.bowlers.reduce((sum, b) => sum + (parseInt(b.total, 10) || 0), 0);
}

async function loadLeagueData() {
  const res = await fetch('leagues-data.json');
  if (!res.ok) throw new Error('Could not load league data (' + res.status + ')');
  return res.json();
}

function latestWeekNum(team) {
  return Math.max(...Object.keys(team.weeks).map(Number));
}
